apiVersion: v1
kind: Service
metadata:
  labels:
    app: back
  name: back-service
  namespace: kubeflow
spec:
  ports:
  - name: grpc-tf-serving
    port: 9085
    targetPort: 9085
    nodePort: 30009
  - name: http-tf-serving
    port: 8500
    targetPort: 8500
    nodePort: 30085
  selector:
    app: back
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: back
  name: back-v1
  namespace: kubeflow
spec:
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: back
        version: v1
    spec:
      containers:
      - env:
          - name: rest_api_port
            value: '8500'
          - name: port
            value: '9085'
          - name: MODEL_NAME
            value: back_light
          - name: MODEL_BASE_PATH
            value: /home/aoi1060/Downloads/fabricModel/serving_dist
        image: tensorflow/serving:2.2.0
        ports:
        - containerPort: 9085
        - containerPort: 8500
        resources:
          limits:
            cpu: "4"
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 1Gi
        imagePullPolicy: IfNotPresent
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 30
          tcpSocket:
            port: 9085
        name: back
        volumeMounts:
        - mountPath: /home/aoi1060/Downloads/fabricModel
          name: tf-volume
      volumes:
      - name: tf-volume
        hostPath:
          path: /home/aoi1060/Downloads/fabricModel
          type: Directory
      nodeSelector:
        name: aoi1060
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  labels:
  name: back-service
  namespace: kubeflow
spec:
  host: back-service
  subsets:
  - labels:
      version: v1
    name: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  labels:
  name: back-service
  namespace: kubeflow
spec:
  gateways:
  - kubeflow-gateway
  hosts:
  - '*'
  http:
  - match:
    - method:
        exact: POST
      uri:
        prefix: /tfserving/models/back
    rewrite:
      uri: /v1/models/back:predict
    route:
    - destination:
        host: back-service
        port:
          number: 8500
        subset: v1
      weight: 100