FROM python:3.6.7
MAINTAINER niyanqin@gmail.com
ADD . /pyfile
RUN pip install --upgrade pip
RUN pip install flask
WORKDIR /pyfile
ENTRYPOINT ["python3", "/pyfile/requestPipeline.py"]


sudo docker build -t yanqin/request_pipeline:v1 .

sudo docker push yanqin/gcc:lab04


sudo docker run -p 8802:8802 --name pipelines_api yanqin/request_pipeline:v1

sudo docker run -it --name pipelines_api --rm -p 8802:8802 yanqin/request_pipeline:v1