# requestPipeline
FROM python:3.6.7
MAINTAINER niyanqin1022@gmail.com
RUN mkdir /pyfile
COPY flaskPip.py /pyfile
RUN pip install --upgrade pip
RUN pip install flask flask_cors kfp kfp-server-api
WORKDIR /pyfile
ENTRYPOINT ["python3", "/pyfile/flaskPip.py"]

sudo docker build -t yanqin/request_pipeline:v6 .
sudo docker push yanqin/request_pipeline:v6
sudo docker pull yanqin/request_pipeline:v6
sudo docker rmi yanqin/request_pipeline:v6
sudo docker run -it --name pipelines_api --rm -p 8882:8882 yanqin/request_pipeline:v2

curl http://127.0.0.1:8882/getList
# paramikoMove

FROM python:3.6.7
MAINTAINER niyanqin1022@gmail.com
ADD . /pyfile
RUN pip install --upgrade pip
RUN pip install paramiko
WORKDIR /pyfile
ENTRYPOINT ["python3", "/pyfile/paramikoMove.py"]


sudo docker build -t yanqin/paramiko_move:v1 .
sudo docker push yanqin/paramiko_move:v1
sudo docker run -it --name paramiko_move_file --rm -p 8803:8803 yanqin/paramiko_move:v1


FROM nginx
MAINTAINER niyanqin1022@gmail.com
# 将dist文件中的内容复制到 /usr/share/nginx/html/ 这个目录下面
COPY dist/  /usr/share/nginx/html/

sudo docker build -t yanqin/image_labeling:v1 .
sudo docker rmi yanqin/image_labeling:v1
sudo docker kill image_label
sudo docker rm image_label
# -p ：配置端口映射，格式是外部访问端口：容器内端口
# -d ：后台运行
# --name : 给容器取名
# 最后有 2 个 gentle-vue,前面一个是给容器取的名字，后面一个是使用的镜像的名字
sudo docker run -p 3000:80 -d --name image_label yanqin/image_labeling:v1

# paramikoMove
FROM python:3.6.7
MAINTAINER niyanqin1022@gmail.com
RUN mkdir /pyfile
COPY ./pyfile/paramikodir.py /pyfile
RUN pip install --upgrade pip
RUN pip install paramiko
WORKDIR /pyfile
ENTRYPOINT ["python3", "/pyfile/paramikodir.py"]

sudo docker build -t yanqin/paramiko_move:v1 .
sudo docker push yanqin/paramiko_move:v1
sudo docker run -it --name zip_label --rm -p 8003:8003 yanqin/zip_label:v1

# create_label
FROM python:3.6.7
MAINTAINER niyanqin1022@gmail.com
RUN mkdir /pyfile
COPY createLabel.py /pyfile
RUN apt-get update
RUN apt-get install -y libgl1-mesa-glx
RUN pip3 install --upgrade pip
RUN pip3 install numpy scipy matplotlib pillow opencv-python zipp
WORKDIR /pyfile
ENTRYPOINT ["python3", "/pyfile/createLabel.py"]

sudo docker build -t yanqin/zip_label:v1 .


# scpMove
FROM python:3.6.7
MAINTAINER niyanqin1022@gmail.com
RUN mkdir /pyfile
COPY scp2ipc.py /pyfile
RUN pip install --upgrade pip
RUN pip install paramiko
WORKDIR /pyfile
ENTRYPOINT ["python3", "/pyfile/scp2ipc.py"]



sudo docker build -t yanqin/paramiko_scp:v1 .
sudo docker push yanqin/paramiko_scp:v1
sudo docker run -it --name paramiko_move_file --rm -p 8803:8803 yanqin/paramiko_scp:v1


sudo docker build -t yanqin/move_pipeline:v1 .

sudo docker push yanqin/gcc:lab04

FROM python:3.6.7
MAINTAINER niyanqin1022@gmail.com
RUN mkdir /pyfile
COPY createLabel.py /pyfile
RUN pip install --upgrade pip
RUN pip install opencv-python
WORKDIR /pyfile
ENTRYPOINT ["python3", "/pyfile/createLabel.py"]

sudo docker build -t yanqin/create_label:v1 .


sudo docker build -t yanqin/tensorflow-opencv:v1 .
FROM ubuntu:16.04

RUN  apt-get update
RUN  apt-get upgrade -y

# Install python3
RUN  apt-get install -y python3

# Install pip
RUN apt-get install -y wget vim
RUN wget -O /tmp/get-pip.py https://bootstrap.pypa.io/get-pip.py
RUN python3 /tmp/get-pip.py
RUN pip install --upgrade pip

# Install tensorflow
RUN pip install -U tensorflow

# Install ffmpeg
RUN  apt-get install -y ffmpeg

# Install moviepy
RUN  pip install -U moviepy

# Install cmake
RUN apt-get update
RUN apt-get install -y build-essential
RUN apt-get install -y cmake

# Install OpenCV
RUN apt-get install -y unzip
RUN wget -P /usr/local/src/ https://github.com/opencv/opencv/archive/3.4.1.zip
RUN cd /usr/local/src/ && unzip 3.4.1.zip && rm 3.4.1.zip
RUN cd /usr/local/src/opencv-3.4.1/ && mkdir build
RUN cd /usr/local/src/opencv-3.4.1/build && cmake -D CMAKE_INSTALL_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr/local/ .. && make -j4 && make install

# Install opencv-python
RUN pip install opencv-python
RUN apt-get install -y libsm6
RUN apt-get install -y libxrender1
RUN apt-get install -y libxext-dev
RUN apt-get install -y libgl1-mesa-glx


github.com,13.250.177.223 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
[140.115.53.52]:20002 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBKOwSgavBJWbAqQIKP3eEop5zwKi5fFmilp3WvjvAoA4h87SW9ZZgiM4cMp1j3jg/snwXpt+/hKOE3Q9pFFf+jI=
[140.115.53.52]:21000 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBKJyUbwEibl7RPQ27w/YJpa3pLa6E6UD0YC94oi+A6R0fHT13WbfPoL40j1L87ER8n+z9dP2/vdmwAvf/gP6CJU=
