# requestPipeline
FROM python:3.6.7
MAINTAINER niyanqin@gmail.com
ADD . /pyfile
RUN pip install --upgrade pip
RUN pip install flask
WORKDIR /pyfile
ENTRYPOINT ["python3", "/pyfile/requestPipeline.py"]


# paramikoMove

FROM python:3.6.7
MAINTAINER niyanqin@gmail.com
ADD . /pyfile
RUN pip install --upgrade pip
RUN pip install paramiko
WORKDIR /pyfile
ENTRYPOINT ["python3", "/pyfile/paramikoMove.py"]


sudo docker build -t yanqin/paramiko_move:v1 .
sudo docker push yanqin/paramiko_move:v1
sudo docker run -it --name paramiko_move_file --rm -p 8803:8803 yanqin/paramiko_move:v1




# paramikoMove

FROM python:3.6.7
MAINTAINER niyanqin1022@gmail.com
RUN mkdir /pyfile
COPY paramikodir.py /pyfile
RUN pip install --upgrade pip
RUN pip install paramiko
WORKDIR /pyfile
ENTRYPOINT ["python3", "/pyfile/paramikodir.py"]



sudo docker build -t yanqin/move_pipeline:v1 .

sudo docker push yanqin/gcc:lab04


sudo docker run -p 8802:8802 --name pipelines_api yanqin/request_pipeline:v1

sudo docker run -it --name pipelines_api --rm -p 8802:8802 yanqin/request_pipeline:v1

rsync -e "ssh -p21000" -auvz --progress --delete --bwlimit=2048 ./models/fabric/ nvidia@140.115.53.52:/home/nvidia/Downloads/fabric
sudo docker run --rm -v blobstorage:/data/ eeacms/rsync \
              rsync -e "ssh -p21000" -auvz --progress --delete --bwlimit=2048 ./models/fabric/ nvidia@140.115.53.52:/home/nvidia/Downloads/fabric




