apiVersion: v1
kind: Service
metadata:
  name: image-api
  namespace: kubeflow
  labels:
    run: image-api
spec:
  type: NodePort
  ports:
    - port: 8882
      nodePort: 30082
      targetPort: 8882
      protocol: TCP
      name: http
  selector:
    run: image-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-api
  namespace: kubeflow
spec:
  selector:
    matchLabels:
      run: image-api
  replicas: 1
  template:
    metadata:
      labels:
        run: image-api
    spec:
      containers:
        - name: imagesapi
          image: yanqin/request_pipeline:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8882