apiVersion: v1
kind: PersistentVolume
metadata:
  name: downloads-pv
  namespace: kubeflow
spec:
  storageClassName: downloads
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/aoi1060/Downloads