apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads-pvc
  namespace: kubeflow
spec:
  storageClassName: downloads
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi