apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nfs-pvc
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nfs-pvc
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: web
          volumeMounts:
            - name: nfs-pv
              mountPath: /home/aoi1060/Downloads/pipelines/nfsdata
      volumes:
        - name: nfs-pv
          persistentVolumeClaim:
            claimName: nfs-pv

---

apiVersion: v1
kind: Service
metadata:
  name: nfs-pvc
  labels:
    app: nfs-pvc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: web
  selector:
    app: nfs-pvc