apiVersion: v1
kind: PersistentVolume
metadata:
  name: fabric-pv
  namespace: kubeflow
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: nvidia@140.115.53.52:/home/nvidia/Downloads/test/