apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fabric-pvc
  namespace: kubeflow
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi