apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nfs-pvc-test
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nfs-pvc-test
    spec:
      containers:
        - name: nginx
          image: nginx:1.7.9
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: web
          volumeMounts:                        #挂载容器中的目录到pvc nfs中的目录
            - name: www
              mountPath: /usr/share/nginx/html
      volumes:
        - name: www
          persistentVolumeClaim:              #指定pvc
            claimName: nfs-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: nfs-pvc-test
  labels:
    app: nfs-pvc-test
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: web              #容器端口或名字
  selector:
    app: nfs-pvc-test