apiVersion: v1
kind: Service
metadata:
  labels:
    app: fabric
  name: fabric-service
  namespace: kubeflow
spec:
  ports:
    - name: grpc-tf-serving
      port: 8501
      targetPort: 8501
      nodePort: 30009
    - name: http-tf-serving
      port: 8500
      targetPort: 8500
      nodePort: 30085
  selector:
    app: fabric
  type: NodePort
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  labels:
  name: fabric-service
  namespace: kubeflow
spec:
  host: fabric-service
  subsets:
    - labels:
        version: v1
      name: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  labels:
  name: fabric-service
  namespace: kubeflow
spec:
  gateways:
    - kubeflow-gateway
  hosts:
    - '*'
  http:
    - match:
        - method:
            exact: POST
          uri:
            prefix: /tfserving/models/fabric
      rewrite:
        uri: /v1/models/fabric:predict
      route:
        - destination:
            host: fabric-service
            port:
              number: 8500
            subset: v1
          weight: 100