apiVersion: v1
kind: Service
metadata:
  labels:
    app: mnist
  name: mnist-service
  namespace: kubeflow
spec:
  ports:
    - name: grpc-tf-serving
      port: 9000
      targetPort: 9000
      nodePort: 30009
    - name: http-tf-serving
      port: 8500
      targetPort: 8500
      nodePort: 30085
  selector:
    app: mnist
  type: NodePort
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  labels:
  name: mnist-service
  namespace: kubeflow
spec:
  host: mnist-service
  subsets:
    - labels:
        version: v1
      name: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  labels:
  name: mnist-service
  namespace: kubeflow
spec:
  gateways:
    - kubeflow-gateway
  hosts:
    - '*'
  http:
    - match:
        - method:
            exact: POST
          uri:
            prefix: /tfserving/models/mnist
      rewrite:
        uri: /v1/models/mnist:predict
      route:
        - destination:
            host: mnist-service
            port:
              number: 8500
            subset: v1
          weight: 100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mnist
  name: mnist-v1
  namespace: kubeflow
spec:
  selector:
    matchLabels:
      app: mnist
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: mnist
        version: v1
    spec:
      containers:
        - env:
            - name: rest_api_port
              value: '8500'
            - name: port
              value: '8501'
            - name: MODEL_NAME
              value: saved_model_half_plus_two_cpu
            - name: MODEL_BASE_PATH
              value: /home/aoi1060/Downloads/serving/tensorflow_serving/servables/tensorflow/testdata
          image: tensorflow/serving:2.2.0
          ports:
            - containerPort: 8501
            - containerPort: 8500
          resources:
            limits:
              cpu: "4"
              memory: 4Gi
            requests:
              cpu: "1"
              memory: 1Gi
          imagePullPolicy: IfNotPresent
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 30
            tcpSocket:
              port: 8501
          name: mnist
          volumeMounts:
            - mountPath: /home/aoi1060/Downloads/serving
              name: tf-volume
      volumes:
        - name: tf-volume
          hostPath:
            path: /home/aoi1060/Downloads/serving
            type: Directory
      nodeSelector:
        name: aoi1060