apiVersion: v1
kind: Service
metadata:
  labels:
    app: mnist
  name: mnist-service
spec:
  ports:
    - name: grpc-tf-serving
      port: 9000
      targetPort: 9000
      nodePort: 30009
    - name: http-tf-serving
      port: 8500
      targetPort: 8500
      nodePort: 30085
  selector:
    app: mnist
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mnist
  name: mnist-v1
spec:
  selector:
    matchLabels:
      app: mnist
  template:
    metadata:
      labels:
        app: mnist
        version: v1
    spec:
      containers:
        - image: emacski/tensorflow-serving:2.2.0-linux_arm
          env:
            - name: rest_api_port
              value: '8500'
            - name: port
              value: '9000'
            - name: MODEL_NAME
              value: saved_model_half_plus_two_cpu
            - name: MODEL_BASE_PATH
              value: /home/nvidia/Downloads/serving/tensorflow_serving/servables/tensorflow/testdata
          ports:
            - containerPort: 8500
            - containerPort: 9000
          imagePullPolicy: IfNotPresent
          name: mnist
          volumeMounts:
            - mountPath: /home/nvidia/Downloads/serving
              name: tf-volume
      volumes:
        - name: tf-volume
          hostPath:
            path: /home/nvidia/Downloads/serving
            type: Directory